---
version: "3.9"

services:
  app:
    image: sepecat/hello-django:base
  web:
    image: sepecat/hello-nginx:base
    volumes_from:
      - app:rw
    ports:
      - "80:80"
    depends_on:
      - app
